name: Build APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        # Usamos la versión de acción mantenida por la comunidad que es más estable
        uses: s0enke/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.11
          subcommand: android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
