name: Build APK

on: [push, pull_request] # Se ejecuta cada vez que subes cambios

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Buildozer
        uses: ArtemSashko/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.11
          subcommand: android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: bin/*.apk